name: jee-demos

services:

  beers-service:
    build: .
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:9080/health/ready" ]
      interval: 2s
      timeout: 10s
      retries: 24
      start_period: 10s
    ports:
      - "9080:9080"
    environment:
      MYSQL_HOSTNAME: "beers-service-db"
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: "beers-db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USE_SSL: "false"
    depends_on:
      beers-service-db:
        condition: service_healthy
    networks:
      - beer-network

  beers-service-db:
    image: mysql:8.4.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "beers-db"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      timeout: 10s
      start_period: 2s
      retries: 10
    networks:
      - beer-network

volumes:
  mysql-data:

networks:
  beer-network:
    driver: bridge
