name: jee-demos-db-only

services:
  mysql:
    image: mysql:latest
    volumes:
      - beers-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beers-db
    ports:
      - "3306:3306"

volumes:
  beers-data:
